|                              `:help motion.txt`                                ||
| -------------------- | -------------------------------------------------------- |
| `<Left>`, `h`        | Move left                                                |
| `<C-H>`, `<BS>`      | Move left                                                |
| `<Down>`, `j`        | Move down one line                                       |
| `<C-J>`, `<NL>`      | Move down one line                                       |
| `gj`, `g<Down>`      | Move down one screen line                                |
| `+`, `<C-M>`, `<CR>` | Move down on the first character                         |
| `_`                  | Move down *count*-1 lines on the first character         |
| `<Up>`, `k`, `<C-P>` | Move up one line                                         |
| `gk`, `g<Up>`        | Move up one screen line                                  |
| `-`                  | Move up on the first character                           |
| `<Right>`, `l`       | Move right                                               |
| `<Space>`            | Move right                                               |
| `<C-Home>`, `gg`     | Go to line *count* or the first line on the first character |
| `G`                  | Go to line *count* or the last line on the first character  |
| `<C-End>`            | Go to line *count* or the last line on the last character   |
| `0`                  | Move to the beginning of the line                        |
| `<Home>`             | Move to the beginning of the line                        |
| `g0`, `g<Home>`      | Move to the beginning of the screen line                 |
| `^`                  | Move to the first character of the line                  |
| `g^`                 | Move to the first character of the screen line           |
| `<End>`, `$`         | Move the end of the line                                 |
| `g$`, `g<End>`       | Move the the last character of the screen line           |
| `g_`                 | Move to the last non-blank character of the line         |
| `H`                  | Move to the top line of the screen                       |
| `M`                  | Move to the center line of the screen                    |
| `L`                  | Move to the bottom line of the screen                    |
| `gm`                 | Move to the center of the screen line                    |
| <tt>&#124;</tt>      | Move to screen column *count*                            |
| *count*`%`           | Move to the line at *count* percentage of the file       |
| `:go` *n*, *n*`go`   | Move to *n* bytes in the buffer                          |
| `(`                  | Move back a sentence                                     |
| `)`                  | Move forward a sentence                                  |
| `{`                  | Move back a paragraph                                    |
| `}`                  | Move forward a paragraph                                 |
| `%`                  | Jump to matching character                               |
| `w`, `<S-Right>`     | Move forward a word                                      |
| `W`, `<C-Right>`     | Move forward a WORD                                      |
| `e`                  | Move forward to the end of word                          |
| `E`                  | Move forward to the end of WORD                          |
| `b`, `<S-Left>`      | Move back a word                                         |
| `B`, `<C-Left>`      | Move back a WORD                                         |
| `ge`                 | Move back to the end of word                             |
| `gE`                 | Move back to the end of WORD                             |
| `t`*x*               | Move right to one character left of the next *x*         |
| `f`*x*               | Move right to the next *x*                               |
| `T`*x*               | Move left to one character right of the next *x*         |
| `F`*x*               | Move left to the next *x*                                |
| `;`                  | Repeat last t, f, T, or F                                |
| `,`                  | Repeat last t, f, T, or F in the opposite direction      |



|                               `:help inserting`                                ||
| --------------- | ------------------------------------------------------------- |
| `i`             | Insert text before the cursor                                 |
| `:startinsert`  | Insert text before the cursor                                 |
| `gi`            | Insert text at the last insertion point                       |
| `I`             | Insert text before the first non-blank character in the line  |
| `gI`            | Insert text at the beginning of the line                      |
| `a`             | Append text after the cursor                                  |
| `A`             | Append text at the end of the line                            |
| `:startinsert!` | Append text at the end of the line                            |
| `o`             | Begin a new line below the cursor and insert text             |
| `O`             | Begin a new line above the cursor and insert text             |



|                                `:help Replace`                                 ||
| --------------- | ------------------------------------------------------------- |
| `R`             | Enter Replace mode                                            |
| `:startreplace` | Enter Replace mode                                            |



|                             `:help vreplace-mode`                              ||
| ---------------- | ------------------------------------------------------------ |
| `gR`             | Enter Virtual Replace mode                                   |
| `:startgreplace` | Enter Virtual Replace mode                                   |



|                            `:help ins-special-keys`                             ||
| ---------------- | ------------------------------------------------------------- |
| `<Esc>`, `<C-[>` | Go back to Normal mode                                        |
| `<C-C>`          | Go back to Normal mode (without triggering autocommands)      |
| `<C-O>`          | Switch to normal mode for one command                         |
| `<C-\><C-O>`     | Switch to normal mode for one command without moving cursor   |
| `<C-@>`          | Insert previously inserted text and leave Insert mode         |
| `<C-A>`          | Insert previously inserted text                               |
| `<C-R>`          | Insert the contents of a register                             |
| `<C-R><C-R>`     | Insert the contents of a register (literally)                 |
| `<C-R><C-O>`     | Insert the contents of a register (no autoindent)             |
| `<C-R><C-P>`     | Insert the contents of a register literally and fix indent    |
| `<C-T>`          | Indent the current line                                       |
| `<C-D>`          | Unindent the current line one shiftwidth                      |
| `0<C-D>`         | Unindent the current line                                     |
| `<C-V>`, `<C-Q>` | Insert a special character                                    |
| `<C-K>`          | Insert digraph                                                |
| `<C-]>`          | Trigger abbreviation                                          |
| `<C-E>`          | Insert the character below the cursor                         |
| `<C-Y>`          | Insert the character above the cursor                         |
| `<Insert>`       | Toggle replace mode                                           |
| `<BS>`, `<C-H>`  | Delete the character before the cursor                        |
| `<Del>`          | Delete the character under the cursor                         |
| `<C-W>`          | Delete the word before the cursor                             |
| `<C-U>`          | Delete all text on the current line before the cursor         |
| `<C-X>`          | Enter completion mode                                         |
| `<C-X><C-L>`     | Complete with whole lines                                     |
| `<C-X><C-N>`     | Complete with words in the current file (searching forward)   |
| `<C-X><C-P>`     | Complete with words in the current file (searching backwards) |
| `<C-X><C-K>`     | Complete with dictionary words                                |
| `<C-X><C-T>`     | Complete with thesaurus words                                 |
| `<C-X><C-I>`     | Complete with words in the current and included files         |
| `<C-X><C-]>`     | Complete with tags                                            |
| `<C-X><C-F>`     | Complete with file names                                      |
| `<C-X><C-D>`     | Complete with definitions or macros                           |
| `<C-X><C-V>`     | Complete with Vim command line                                |
| `<C-X><C-U>`     | Complete with user defined completion                         |
| `<C-X><C-O>`     | Complete with omni completion                                 |
| `<C-X>s`         | Complete with spelling suggestions                            |
| `<C-X><C-E>`     | Stop completion with original text                            |
| `<C-X><C-Y>`     | Stop completion with current selection                        |



|                                  visual modes                                  ||
| ------------ | ---------------------------------------------------------------- |
| `v`          | Enter visual (character) mode                                    |
| `V`          | Enter visual line mode                                           |
| `<C-V>`      | Enter visual block mode                                          |



|                               `:help change.txt`                               ||
| ------------ | ---------------------------------------------------------------- |
| `<Del>`, `x` |                                                                  |
| `X`          |                                                                  |
| `d`          |                                                                  |
| `dd`         |                                                                  |
| `D`          |                                                                  |
| `:delete`    |                                                                  |
| `J`          |                                                                  |
| `gJ`         |                                                                  |
| `:join`      |                                                                  |
| `c`          | Change (delete and enter insert mode)                            |
| `d`          | Delete                                                           |
| `y`          | Yank (copy)                                                      |
| `~`          | Swap case                                                        |
| `g~`         | Swap case                                                        |
| `gu`         | Make lowercase                                                   |
| `gU`         | Make uppercase                                                   |
| `!`          | Filter through an external program                               |
| `=`          | Indent                                                           |
| `==`         | Indent lines                                                     |
| `g?`         | Encode with rot13                                                |
| `>`          | Indent right                                                     |
| `>>`         | Indent line right                                                |
| `<`          | Indent left                                                      |
| `<<`         | Indent line left                                                 |
| `!`          | Filter text through a command                                    |
| `!!`         | Filter lines through a command                                   |
| `:`*range*`!`*command* | Filter *range* through *command*                       |
| `:s`         | Substitute (see `:help :s`)                                      |
| `:&`, `&`    | Repeat last substitution                                         |



|                              `:help text-objects`                              ||
| ------------ | ---------------------------------------------------------------- |
| `a`*c*       | Text object *c* including delimiters                             |
| `i`*c*       | Text object *c* inside delimiters                                |
| `aw`         | Word                                                             |
| `aw`         | WORD                                                             |
| `as`         | Sentence                                                         |
| `ap`         | Paragraph                                                        |
| `a'`         | `'`-quoted string                                                |
| `a"`         | `"`-quoted string                                                |
| `a[`, `a]`   | [] block                                                         |
| `a(`, `a)`   | () block                                                         |
| `a<`, `a>`   | &lt;&gt; block                                                   |
| `a{`, `a}`   | {} block                                                         |
| `at`         | Tag (HTML, XML, etc.)                                            |



|                             `:help inserting-file`                             ||
| -------------------- | -------------------------------------------------------- |
| `:r` *file*          | Insert *file* below the current line                     |
| `:`*range*`r` *file* | Insert *file* below the last line in *range*             |
| `:r !` *command*     | Insert the output of *command* below the current line    |



|                                window commands                                 ||
| ------------------- | --------------------------------------------------------- |
| `<C-W>n`, `:new`    |                                                           |
| `<C-W>s`, `:split`  |                                                           |
| `<C-W>v`, `:vsplit` |                                                           |
| `<C-W>o`, `:only`   |                                                           |
| `<C-W>c`, `:close`  |                                                           |
| `<C-W>q`, `:q[uit]` |                                                           |
| `<C-W>=`            |                                                           |
| `<C-W><C-W>`        |                                                           |
| `<C-W>h`            |                                                           |
| `<C-W>j`            |                                                           |
| `<C-W>k`            |                                                           |
| `<C-W>l`            |                                                           |



|                                    display                                     ||
| ------------ | ---------------------------------------------------------------- |
| `<C-G>`      | Show filename and position in status line                        |
| `g<C-G>`     | Show detailed position information in status line                |
| `zz`         |                                                                  |
| `zt`         |                                                                  |
| `zb`         |                                                                  |
| `zf`         |                                                                  |
| `zF`         |                                                                  |
| `:fold`      |                                                                  |
| `zc`         |                                                                  |
| `zo`         |                                                                  |



|                              `:help options.txt`                               ||
| --------------------- | ------------------------------------------------------- |
| `:set`                | Print non-default options                               |
| `:set all`            | Print all options                                       |
| `:set` *option*`?`    | Print the value of *option*                             |
| `:set no`*option*     | Turn *option* off                                       |
| `:set inv`*option*, `:set` *option*`!` | Toggle *option*                        |
| `:set` *option*`&`    | Reset *option* to its default value                     |
| `:set` *option*`&vi`  | Reset *option* to its `vi` default value                |
| `:set` *option*`&vim` | Reset *option* to its Vim default value                 |
| `:set all&`           | Reset all options to their default values               |
| `:set` *option*`=`*value*, `:set` *option*`:`*value* | Set *option* to *value*  |
| `:set` *option*`+=`*value* | Add numeric *value* or append string *value* to *option* |
| `:set` *option*`^=`*value* | Multiply numeric *value* or prepend string *value* to *option* |
| `:set` *option*`+=`*value* | Subtract numeric *value* or remove string *value* from *option* |
| `:setlocal`           | Print or set values local to the current buffer or window |
| `:setglobal`          | Print or set global values without modifying local values |
| `:setlocal` *option*`<` | Set the local value of *option* to its global value   |
| `:set` *option*`<`    | Remove the local value of *option*                      |
| `:options`, `:browse set` | Open a window to view and set all options           |
|                                Boolean options                                 ||
| `:set compatible`     | Turn on strict `vi` compatibility                       |
| `:set incsearch`      | Look ahead on searches                                  |
| `:set ignorecase`     | Ignore case in searches                                 |
| `:set smartcase`      | Override `ignorecase` when searches contain upper case  |
| `:set hlsearch`       | Highlight any matches to the previous search pattern    |
| `:set cursorline`     | Highlight the screen line where the cursor is           |
| `:set cursorcolumn`   | Highlight the screen column where the cursor is         |
| `:set number`         | Show line numbers in front of each line                 |
| `:set relativenumber` | Show line numbers relative to the current line          |
| `:set wrap`           | Show long lines wrapped on the screen                   |
| `:set expandtab`      | Insert spaces instead of tab characters                 |
| `:set autoindent`     | Match indent of previous line when starting a new line  |
| `:set smartindent`    | Try to guess what you want when autoindenting           |
| `:set cindent`        | Use C rules when autoindenting                          |
| `:set shiftround`     | Round indentation to multiples of `shiftwidth`          |
| `:set smarttab`       | Change the rules when hitting `<Tab>` or `<BS>`         |
| `:set spell`          | Turn on spell checking                                  |
| `:set hidden`         | Allows switching away from modified buffers             |
| `:set cursorbind`     | Cursors in all windows with this set move together      |
| `:set scrollbind`     | All windows with this set scroll together               |
| `:set paste`          | Disables any automatic formatting                       |
| `:set list`           | Show line endings and special characters                |
| `:set showmatch`      | Jump to the matching bracket when inserting one         |
| `:set ruler`          | Show the line and column number in the status line      |
| `:set showcmd`        | Show partial commands in the status line                |
| `:set showmode`       | Show a message in the status line for some modes        |
|                                Assign a number                                 ||
| `:set textwidth=`*n*    | Wrap text at *n* columns                              |
| `:set wrapmargin=`*n*   | Wrap text at *n* columns from the right of the screen |
| `:set shiftwidth=`*n*   | Use *n* spaces for indentation                        |
| `:set tabstop=`*n*      | Set tabs to *n* spaces                                |
| `:set scrolloff=`*n*    | Show *n* screen lines above and below the cursor      |
|                             Various other settings                             ||
| `:set spelllang=`*lang* | Set spell checking language to *lang*                 |
| `:set fileformat=`*f*   | Set file format to *f* (`unix`, `dos`, or `mac`)      |
| `:set colorcolumn=`*list* | Highlight the columns in *list*                     |
| `:set filetype=`*t*   | Set filetype to *t* and trigger associated autocommands |
| `:set formatoptions=`*list* | Set format options to *list* (see `:help fo-table`) |
| `:set mouse=`*list*   | Enable mouse and set options to *list* (see `:help mouse`) |
| `:set matchpairs=`*list* | Set characters to match with `showmatch`, `%`, etc. to *list* |
| `:set statusline=`*string* | Set the status line to *string* (see `:help status-line`) |
| `:set virtualedit=`*list* | Allow the cursor to be positioned past the end of text (see `:help virtualedit`) |



|                               `:help registers`                                ||
| ------------ | ---------------------------------------------------------------- |
| `"a` to `"z` | Named registers (replace)                                        |
| `"A` to `"Z` | Named registers (append)                                         |
| `""`         | Unnamed register (contains last delete or yank)                  |
| `"0`         | Most recent yank                                                 |
| `"1` to `"9` | Recent deletes or changes                                        |
| `"-`         | Last delete less than one line                                   |
| `".`         | Last inserted text                                               |
| `"/`         | Last search pattern                                              |
| `":`         | Last command line                                                |
| `"%`         | Current file name                                                |
| `"#`         | Alternate file name                                              |
| `"+`         | Clipboard contents                                               |
| `"*`         | X11 selection contents                                           |
| `"~`         | Dropped text                                                     |
| `"_`         | Black hole register                                              |
| `"=`         | Expression register                                              |
| `:reg`, `:registers`, `:dis`, `:display` | Print registers                      |



|                              `:help mark-motions`                                 ||
| --------------- | ---------------------------------------------------------------- |
| `m`*c*          | Set mark *c*                                                     |
| `:mark` *c*     | Set mark *c*                                                     |
| `:k`*c*         | Set mark *c*                                                     |
| `'`*c*          | Jump to mark *c* ([a-z] in current buffer, [A-Z] in any buffer)  |
| <tt>\`</tt>*c*  | Jump to mark *c* ([a-z] in current buffer, [A-Z] in any buffer)  |
| `:marks`        | List marks                                                       |
| `:delmarks` *c* | Delete mark(s) *c*                                               |
| `:delmarks!`    | Delete all marks                                                 |
| `'[`            | Beginning of last changed or yanked text                         |
| `']`            | End of last changed or yanked text                               |
| `'<`            | Beginning of last visual area                                    |
| `'>`            | End of last visual area                                          |
| `''`            | Last jump or mark position                                       |
| `'"`            | Last position when exiting the current buffer                    |
| `'^`            | Position where insert mode was last stopped                      |
| `'.`            | Position of the last change                                      |
| `'(`            | Start of the current sentence                                    |
| `')`            | End of the current sentence                                      |
| `'{`            | Start of the current paragraph                                   |
| `'}`            | End of the current paragraph                                     |



|                              `:help jump-motions`                              ||
| ---------------- | ------------------------------------------------------------ |
| `:jumps`         | Print the jump list                                          |
| `<C-O>`          | Move to older position in jump list                          |
| `<C-I>`, `<Tab>` | Move to older position in jump list                          |



|                               `:help changelist`                               ||
| ------------ | ---------------------------------------------------------------- |
| `:changes`   | Print the change list                                            |
| `g;`         | Move to older position in change list                            |
| `g,`         | Move to newer position in jump list                              |



|                               `:help formatting`                               ||
| ----------------- | ----------------------------------------------------------- |
| `:center`         | Center lines                                                |
| `:right`          | Right-align lines                                           |
| `:left`           | Left-align lines                                            |
| `gq`              | Format lines                                                |
| `gqgq`, `gqq`     | Format the current line                                     |
| `gw`              | Format lines and restore cursor position                    |
| `gwgw`, `gww`     | Format the current line and restore cursor position         |



|                                buffer commands                                 ||
| ------------ | ---------------------------------------------------------------- |
| `:ls`        |                                                                  |
| `:bd`        |                                                                  |
| `:enew`      |                                                                  |
| `:bn`        |                                                                  |
| `:bp`        |                                                                  |
| `:bufdo`     |                                                                  |



|                                    exiting                                     ||
| ------------ | ---------------------------------------------------------------- |
| `:x`, `ZZ`   |                                                                  |
| `:xa`        |                                                                  |
| `:w`         |                                                                  |
| `:wa`        |                                                                  |
| `:wq`        |                                                                  |
| `:wqa`       |                                                                  |
| `:q`         |                                                                  |
| `:q!`, `ZQ`  |                                                                  |
| `:qa`        |                                                                  |



|                                     random                                     ||
| ----------------- | ----------------------------------------------------------- |
| `:g`              |                                                             |
| `:v`              |                                                             |
| `:echo`           |                                                             |
| `:windo`          |                                                             |
| `:args`           |                                                             |
| `:argdo`          |                                                             |
| `:tabnew`         |                                                             |
| `q:`, `:<C-F>`    |                                                             |
| `q/`              |                                                             |
| `q?`              |                                                             |
| `:e`              |                                                             |
| `:shell`          |                                                             |
| `gf`              |                                                             |
| `gF`              |                                                             |



|                              `:help pattern.txt`                               ||
| ------------ | ---------------------------------------------------------------- |
| `.`          | Any character (other than a newline)                             |
| `\.`         | Any character (across lines)                                     |
| <tt>&#92;</tt><tt>&#124;</tt> | Or                                              |
| `\&`         | And (matches from the beginning of the line)                     |
|                                    Grouping                                    ||
| `\(`*pattern*`\)` | Grouping for capture or repetition                          |
| `\%(`*pattern*`\)` | Grouping without capture                                   |
|                                    Anchors                                     ||
| `^`          | Beginning of the line                                            |
| `$`          | End of the line                                                  |
| `\<`         | Left word boundary                                               |
| `\>`         | Right word boundary                                              |
| `\_^`        | Start of line (in a multi-line match)                            |
| `\_$`        | End of line (in a multi-line match)                              |
| `\%^`        | Start of the file                                                |
| `\%$`        | End of the file                                                  |
|                                   Repetition                                   ||
| `*`          | 0 or more                                                        |
| `\{-\}`      | 0 or more, non-greedy                                            |
| `\?`         | 0 or 1                                                           |
| `\+`         | 1 or more                                                        |
| `\{`*n*`\}`  | Exactly *n*                                                      |
| `\{,`*m*`\}` | No more than *m*                                                 |
| `\{`*n*`,`*m*`\}` | At least *n*, but no more than *m*                          |
| `\{-`*n*`,`*m*`\}` | At least *n*, but no more than *m*, non-greedy             |
|                               Character classes                                ||
| `[abc]`      | Any of the characters `a`, `b`, or `c`                           |
| `[a-c]`      | Any of the characters `a` through `c`                            |
| `[^abc]`     | Any character **not** `a`, `b`, or `c`                           |
| `[[:alnum:]]` | Any alphanumeric character                                      |
| `[[:alpha:]]` | Any alphabetical character                                      |
| `[[:upper:]]` | Any upper case character                                        |
| `[[:lower:]]` | Any lower case character                                        |
| `[[:digit:]]` | Any digit [0-9]                                                 |
| `[[:blank:]]` | Any horizontal whitespace character                             |
| `[[:space:]]` | Any whitespace character                                        |
| `[[:cntrl:]]` | Any control character                                           |
| `[[:punct:]]` | Any punctuation character                                       |
| `[[:print:]]` | Any printable character                                         |
| `[[:graph:]]` | Any non-space printable character                               |
|                                 Backreferences                                 ||
| <tt>&#92;</tt>*n* | Previous grouped match *n*                                  |
| `&`          | Entire left-hand side match                                      |
|                             Zero-width assertions                              ||
| `\@=`        | Zero-width positive look-ahead                                   |
| `\@!`        | Zero-width negative look-ahead                                   |
| `\@<=`       | Zero-width positive look-behind                                  |
| `\@<!`       | Zero-width negative look-behind                                  |
| `\zs`        | Start of match (the rest is zero-width)                          |
| `\ze`        | End of match (the rest is zero-width)                            |



|                                 `:help :help`                                  ||
| --------------------- | ------------------------------------------------------- |
| `:help`               | Open help                                               |
| `<C-]>`, `<C-LeftMouse>`, `g<LeftMouse>` | Jump to a tag                        |
| `<C-T>`, `<C-D>`      | Jump back to previous help tag                          |
| `:help` *subject*     | Open help and jump to *subject*                         |
| `:helpgrep` *pattern* | Search help for *pattern* and jump to first match       |
| `:cnext`              | Jump to the next match                                  |
| `:cwindow`            | Show matches in the quickfix window                     |



|                              Command-line options                              ||
| ------------------- | --------------------------------------------------------- |
| `vim` *files*       | Open terminal Vim to edit *files*                         |
| `gvim`, `vim -g`    | Open GUI Vim                                              |
| `vimdiff`, `vim -d` | Open Vim in diff mode                                     |
| `vim -`             | Edit stdin                                                |
